export const API_PREFIX = '/api/v1'
export const API_MEMBER_LIST_GET = '/members'
export const API_PROJECT_LIST_GET = '/projects'
export const API_RESOURCE_LIST_GET = '/resources'
export const API_RESOURCE_UPDATE = '/resources'
